import os
import argparse

'''
This Python generates the .xyt files from the given .jpeg or .wsq image,
in addition to the .xyt files, the mindtct, program of NBIS also generates
other formats, which can be removed using a seperate Pyhton file named
'delete_files.py'. Provide the path of the directory containing the images
and path of the directory to store the files generated by the mindtct program.
Make sure that mindtct in available on your path for this code to work
correctly, if your don't want to add mindtct to yout path, change it here.
'''
# Change this according to path in your system,
# Do not change if nfiq is added to the path
nfiq_path = "nfiq"
os_path_join = os.path.join
def processNFIQ(path,nfiqFile):
    if path[-1] == '/':
        path = path[:-1]
    # Running nfiq using os.system(),
    # See manual for nfiq for details on argument and parameters
    for file in os.listdir(path):
        os.system('nfiq -d {} {}/*.jpg >> {}'
                  .format(os.path.join(path, file), path,nfiqFile))
if __name__ == "__main__":
	 # code for cli arguments
    parser = argparse.ArgumentParser(description='desc')
    parser.add_argument('-p', '--path', help='Required. Path to the directory', required=True)
    parser.add_argument('-s', '--save_path', default="result.txt",help='Required. to save result file', required=True)
    args = vars(parser.parse_args())
    path = args['path']
    nfiqFile=args['save_path']
    # Running bozorth3 using os.system(),
    # See manual for bozorth3 for details on argument and parameters
    for file in os.listdir(path):
        os.system('nfiq -d {} {}/*.jpg >> {}'
                  .format(os.path.join(path, file), path,nfiqFile))
